spring:
  application:
    name: gateway-service
  cloud:
    config:
      uri: http://config-service:8888
  config:
    import: optional:configserver:http://config-service:8888
    cloud:
      config:
        profile: native