spring:
  application:
    name: character-service
  datasource:
    url: jdbc:postgresql://localhost:5432/character_service_db
    username: character
    password: character
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8081
