spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: character-service-route
          uri: lb://character-service
          predicates:
            - Path=/characters/**
          filters:
            - RewritePath=/characters(?<segment>/.*)?, /api/v1/characters${segment}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8080
