spring:
  application:
    name: gateway-service
#  cloud:
#    gateway:
#      routes:
#        - id: character-service
#          predicates:
#            - ...
#          uri: ...
#        - id: authentication-service
#          predicates:
#            - ...
#          uri: ...
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
